import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Instagram, MapPin, MessageCircle, Phone, Ruler, Scissors, Sparkles, Star } from 'lucide-react';
import { whatsappNumber } from '@/src/data';

const wa = (text: string) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(text)}`;

export default function LandingPage() {
  return <div className="min-h-screen bg-[var(--paper)]">
    <header className="site-header"><div className="shell flex h-[82px] items-center justify-between">
      <Link href="/" className="brand-lockup"><Image src="/images/logo-mark.png" alt="Maison Prisca Atelier" width={46} height={46} /><span><strong className="serif block text-xl uppercase tracking-[.07em]">Maison Prisca</strong><small>Atelier · Lagos</small></span></Link>
      <nav className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#about">The atelier</a><a href="#services">Services</a><a href="#contact">Contact</a><Link href="/store" className="btn btn-dark !px-5 !py-2.5">Enter collection <ArrowRight size={16} /></Link></nav>
      <Link href="/store" className="btn btn-dark !px-4 !py-2.5 text-sm md:hidden">Shop</Link>
    </div></header>
    <main>
      <section className="hero-luxury relative overflow-hidden"><div className="shell grid gap-12 py-20 md:grid-cols-[1.05fr_.95fr] md:items-center md:py-28"><div className="max-w-xl"><p className="eyebrow"><Sparkles size={14} /> Lagos · Nigeria · Since 2021</p><h1 className="serif mt-5 text-6xl leading-[.9] sm:text-8xl">The art of being <em>unforgettable.</em></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[var(--muted)]">Maison Prisca is a Lagos fashion atelier creating confident, body-aware pieces around your occasion, measurements and personality.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/store" className="btn btn-grad">Explore collection <ArrowRight size={17} /></Link><a href={wa('Hello Maison Prisca, I would like to book a private fitting.')} className="btn btn-line">Book a fitting</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--muted)]"><span>Made in Lagos</span><span>Private fittings</span><span>WhatsApp concierge</span></div></div><div className="hero-art arch relative mx-auto aspect-[4/5] w-full max-w-sm"><div className="absolute inset-0 grid place-items-center p-10"><Image src="/images/logo-full.png" alt="Maison Prisca Lagos Atelier" width={520} height={275} className="w-full object-contain" /></div><div className="absolute bottom-6 left-6 right-6 flex justify-between text-[10px] uppercase tracking-[.16em] text-[var(--rose-deep)]"><span>Festac Town</span><span>01 / 01</span></div></div></div></section>
      <section className="border-b border-[var(--line)] bg-[var(--white)]"><div className="shell grid gap-4 py-6 sm:grid-cols-3"><div className="flex items-center gap-3"><Star size={18} className="text-[var(--gold)]" /><div><strong className="block text-sm">Considered design</strong><span className="text-xs text-[var(--muted)]">Every detail has a reason</span></div></div><div className="flex items-center gap-3"><Ruler size={18} className="text-[var(--gold)]" /><div><strong className="block text-sm">Fit, not guesswork</strong><span className="text-xs text-[var(--muted)]">Guided measurements and counsel</span></div></div><div className="flex items-center gap-3"><MessageCircle size={18} className="text-[var(--gold)]" /><div><strong className="block text-sm">A human experience</strong><span className="text-xs text-[var(--muted)]">Direct WhatsApp concierge</span></div></div></div></section>
      <section id="about" className="shell grid gap-12 py-24 md:grid-cols-2 md:items-center"><div className="atelier-card arch relative aspect-[4/5] max-w-md"><div className="absolute inset-0 grid place-items-center p-12 text-center"><span className="monogram text-7xl text-[var(--rose)]">P</span><p className="serif mt-3 text-3xl">Made around you.</p><p className="mt-4 text-sm leading-6 text-[var(--muted)]">One woman. One occasion. One unforgettable fit.</p></div></div><div><p className="eyebrow">The atelier</p><h2 className="serif mt-4 text-5xl leading-tight">Luxury is the feeling of being perfectly understood.</h2><p className="mt-6 leading-8 text-[var(--muted)]">From Ankara and Adire to bridal, pageant and occasion looks, every piece is designed with care in our Lagos atelier. We take time to understand your fit, your date and the feeling you want to carry into the room.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div><strong className="serif text-3xl">01</strong><p className="mt-1 text-sm text-[var(--muted)]">Tell us the moment</p></div><div><strong className="serif text-3xl">02</strong><p className="mt-1 text-sm text-[var(--muted)]">Shape the details</p></div><div><strong className="serif text-3xl">03</strong><p className="mt-1 text-sm text-[var(--muted)]">Wear your presence</p></div></div></div></section>
      <section id="services" className="border-y border-[var(--line)] bg-[var(--blush)]/25 py-20"><div className="shell"><p className="eyebrow">Choose your experience</p><h2 className="serif mt-3 text-5xl">Your moment, our craft.</h2><div className="mt-10 grid gap-4 md:grid-cols-3"><article className="service-card"><Scissors size={24} className="text-[var(--gold)]" /><h3 className="serif mt-8 text-3xl">Bespoke commissions</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">A one-of-one piece shaped from your references, your proportions and your occasion.</p><a href={wa('Hello Maison Prisca, I would like to discuss a bespoke commission.')} className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--rose-deep)]">Discuss a commission <ArrowRight size={14} /></a></article><article className="service-card"><Sparkles size={24} className="text-[var(--gold)]" /><h3 className="serif mt-8 text-3xl">Bridal & occasion</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Soft drama, intelligent fit and the confidence to stay present in every photograph.</p><a href={wa('Hello Maison Prisca, I would like to discuss bridal or occasion dressing.')} className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--rose-deep)]">Start your story <ArrowRight size={14} /></a></article><article className="service-card"><Ruler size={24} className="text-[var(--gold)]" /><h3 className="serif mt-8 text-3xl">Ready-to-wear</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">A considered edit of pieces made to move beautifully from your wardrobe to your calendar.</p><Link href="/store" className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--rose-deep)]">Shop the edit <ArrowRight size={14} /></Link></article></div></div></section>
      <section className="shell py-24"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow justify-center">A note from the atelier</p><blockquote className="serif mt-6 text-4xl leading-tight sm:text-5xl">“Your body is not a problem to solve. It is the canvas every beautiful detail begins with.”</blockquote><p className="mt-6 text-sm text-[var(--muted)]">— Maison Prisca</p></div></section>
      <section className="border-y border-[var(--line)] py-16"><div className="shell grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">The signature edit</p><h2 className="serif mt-3 text-5xl">Pieces with presence.</h2><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">Browse published pieces, explore every product photo, choose your size and send your order directly to WhatsApp.</p></div><Link href="/store" className="btn btn-dark">View collection <ArrowRight size={17} /></Link></div></section>
    </main>
    <footer id="contact" className="footer-luxury py-16 text-white"><div className="shell grid gap-12 md:grid-cols-2"><div><Image src="/images/logo-full-white.png" alt="Maison Prisca Atelier" width={340} height={180} className="w-[220px] object-contain" /><p className="mt-6 max-w-md leading-7 text-white/65">Bespoke, bridal, occasion and ready-to-wear fashion designed in Festac, Lagos.</p><div className="mt-8 flex flex-wrap gap-3"><a href={wa('Hello Maison Prisca, I would like to make an enquiry.')} className="btn btn-grad"><MessageCircle size={17} /> WhatsApp the atelier</a><Link href="/store" className="btn btn-ghost-light">Visit collection</Link></div></div><div className="md:justify-self-end"><p className="eyebrow" style={{ color: 'var(--blush)' }}>Visit &amp; connect</p><div className="mt-5 grid gap-4 text-sm text-white/75"><p className="flex items-start gap-3"><MapPin size={18} className="shrink-0 text-[var(--blush)]" />401 Road, I Close, Festac Town, Lagos</p><a href={wa('Hello Maison Prisca, I would like to make an enquiry.')} className="flex items-center gap-3"><Phone size={18} className="text-[var(--blush)]" />0814 500 0582</a><div className="flex gap-2"><a href="#" className="social-icon"><Instagram size={17} /></a><a href="#" className="social-icon"><MessageCircle size={17} /></a></div></div></div></div><div className="shell mt-12 flex flex-wrap items-center justify-between gap-3 border-t border-white/15 pt-5 text-xs text-white/40"><span>© 2026 Maison Prisca Atelier · Lagos.</span><a href={process.env.NEXT_PUBLIC_ADMIN_SITE_URL || 'https://maison-prisca-admin.netlify.app'} className="underline">Private atelier access</a></div></footer><a href={wa('Hello Maison Prisca, I would like to make an enquiry.')} className="whatsapp-float" aria-label="Chat on WhatsApp"><MessageCircle size={22} /></a>
  </div>;
}
