import { cartStorageKey,type CartItem,type Product } from './data';
const legacyCartKeys=['maison-prisca-cart-v2','maison-prisca-cart'];
let memoryCart:CartItem[]=[];
const keyOf=(item:CartItem)=>`${item.product.$id||item.product.slug}::${item.size}`;
export function mergeCart(items:CartItem[]):CartItem[]{const merged=new Map<string,CartItem>();for(const item of items){if(!item?.product||!item.size||!Number.isFinite(Number(item.quantity))||Number(item.quantity)<=0)continue;const normalized={...item,quantity:Math.max(1,Math.floor(Number(item.quantity)))};const key=keyOf(normalized);const existing=merged.get(key);merged.set(key,existing?{...existing,quantity:existing.quantity+normalized.quantity}:normalized);}return [...merged.values()];}
export function readCart():CartItem[]{if(typeof window==='undefined')return[];try{const current=window.localStorage.getItem(cartStorageKey);if(current!==null){const value=JSON.parse(current);memoryCart=Array.isArray(value)?mergeCart(value):[];return memoryCart;}for(const legacyKey of legacyCartKeys){const old=window.localStorage.getItem(legacyKey);if(old){const value=JSON.parse(old);if(Array.isArray(value)){memoryCart=mergeCart(value);return memoryCart;}}}}catch{return memoryCart;}return memoryCart;}
export function writeCart(items:CartItem[]):boolean{memoryCart=mergeCart(items);if(typeof window==='undefined')return false;try{window.localStorage.setItem(cartStorageKey,JSON.stringify(memoryCart));return true;}catch{return false;}}
export function addCartItem(items:CartItem[],product:Product,size:string,quantity:number):CartItem[]{return mergeCart([...items,{product,size,quantity}]);}
export function reconcileCart(items:CartItem[],currentProducts:Product[]){const current=new Map(currentProducts.map(product=>[product.$id||product.slug,product]));const valid:CartItem[]=[];const unavailable:string[]=[];for(const item of mergeCart(items)){const product=current.get(item.product.$id||item.product.slug)||currentProducts.find(candidate=>candidate.slug===item.product.slug);if(!product||product.status!=='Published'){unavailable.push(item.product.name);continue;}valid.push({...item,product});}return {items:mergeCart(valid),unavailable};}
